In [18]:
import gender_guesser.detector as gender

In [3]:
import pandas as pd

In [4]:
import csv

In [19]:
d = gender.Detector(case_sensitive=False)

In [4]:
df_all_un = pd.read_csv('../amazon_undecided_cleaned.csv',sep='|',names=['ReviewerID', 'ProductID', 'Name', 'Gender','Helpfulness', 'Review', 'Rating','Timestamp'])

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ReviewerID,ProductID,Name,Gender,Helpfulness,Review,Timestamp
Rating,,,,,,,
1.0,2221647,2221647,2221441,2221647,2221647,2220942,2221647
2.0,1410509,1410509,1410383,1410509,1410509,1410173,1410509
3.0,2296558,2296558,2296393,2296558,2296558,2296201,2296558
4.0,4937097,4937097,4936783,4937097,4937097,4936173,4937097
5.0,15251851,15251851,15250731,15251851,15251851,15248303,15251851
1.0,1475325,1475325,1475147,1475325,1475325,1474806,1475325
2.0,938108,938108,938030,938108,938108,937905,938108
3.0,1523867,1523867,1523706,1523867,1523867,1523596,1523867
4.0,3280167,3280167,3279791,3280167,3280167,3279536,3280167
5.0,10214756,10214756,10213931,10214756,10214756,10212426,10214756
andy,2,2,2,2,2,2,2
unknown,351,351,351,351,351,351,351

In [10]:
df_all_un = df_all_un[(df_all_un['Rating']!='andy')&(df_all_un['Rating']!='unknown')]

In [13]:
df_all_un.groupby('Rating').count()

,ReviewerID,ProductID,Name,Gender,Helpfulness,Review,Timestamp
Rating,,,,,,,
1.0,3696972,3696972,3696588,3696972,3696972,3695748,3696972
2.0,2348617,2348617,2348413,2348617,2348617,2348078,2348617
3.0,3820425,3820425,3820099,3820425,3820425,3819797,3820425
4.0,8217264,8217264,8216574,8217264,8217264,8215709,8217264
5.0,25466607,25466607,25464662,25466607,25466607,25460729,25466607

In [12]:
df_all_un['Rating'] = df_all_un['Rating'].astype('float32')

In [10]:
import csv
import re

In [1]:
count = 0
lines_c = 0
count_1 = 0
with open('../amazon_undecided_cleaned.csv','w') as ft:
    with open('../amazon_undecided.csv') as fs:
        for line in fs:
            lines_c+=1
            if lines_c==1:
                continue
            if lines_c%1000000==0:
                print(lines_c)
            temp = line.strip().split('|')
            if len(temp)==8:
                try:
                    r = float(temp[6])
                    t = float(temp[7])
                    ft.write(line)
                except:
                    count_1+=1
            else:
                count+=1
            
print ('count: ',count)    
print ('count_1: ',count_1)

1000000
2000000
3000000
4000000
5000000
6000000
7000000
8000000
9000000
10000000
11000000
12000000
13000000
14000000
15000000
16000000
17000000
18000000
19000000
20000000
21000000
22000000
23000000
24000000
25000000
26000000
27000000
28000000
29000000
30000000
31000000
32000000
33000000
34000000
35000000
36000000
37000000
38000000
39000000
40000000
41000000
42000000
43000000
count:  8486
count_1:  0

In [2]:
count = 0
lines_c = 0
count_1 = 0
with open('../amazon_gender_new/amazon_unknown_cleaned.csv','w') as ft:
    with open('../amazon_gender_new/amazon_unknown.csv') as fs:
        for line in fs:
            lines_c+=1
            if lines_c==1:
                continue
            if lines_c%1000000==0:
                print(lines_c)
            #print(line) 
            temp = line.strip().split('|')
            #print(len(temp))
            if len(temp)==9:
                try:
                    r = float(temp[7])
                    t = float(temp[8])
                    ft.write(line)
                except:
                    count_1+=1
            else:
                count+=1
            
print ('count: ',count)    
print ('count_1: ',count_1)

1000000
2000000
3000000
4000000
5000000
6000000
7000000
8000000
9000000
10000000
11000000
12000000
13000000
14000000
15000000
16000000
17000000
18000000
19000000
20000000
21000000
22000000
23000000
24000000
25000000
26000000
27000000
28000000
29000000
30000000
31000000
32000000
33000000
34000000
35000000
36000000
37000000
count:  5719
count_1:  6234

In [13]:
with open('../amazon_gender_new/amazon_unknown_cleaned.csv') as fs:
    for line in fs:
        temp=line.strip().split('|')
        if len(temp)!=9:
            print(line)
            print(temp)
            break

In [13]:
df_t = pd.read_csv('../amazon_gender_new/test_file.csv',sep='|')

In [14]:
df_t

,575120,A11P2ZHW393JIA,1581809085,"A G. F. you ""Mindy""",unknown,"0,0","I LOVE this book!!! I have so much fun making the projects in this book, it I filled with full mosaic ideas that are contemporary and out of the normal broken china and tile mosaic book. This is one of the best books in my library. This author also wrote another book like this and that is my next favorite book. If you like making mosaics that are unique and out-of-the box I high recommend this fun book.",5.0,1370044800
0,459395,A11CEGS0750Y1R,B00IMQM7K0,avid reader,unknown,"1,1",This was one of the best books I have read on ...,5.0,1393632000
1,459505,A11CF0HPJQNT8P,0983072132,"D. Halbert ""Hal""",unknown,"2,2",Regency romance at its finest. A misunderstoo...,5.0,1384560000
2,459506,A11CF0HPJQNT8P,B002UR3TA4,"D. Halbert ""Hal""",unknown,"12,18",This is a toy that is hard plastic with a marb...,1.0,1264809600

In [14]:
import string
translator = str.maketrans('', '', string.punctuation)

In [8]:
df_sample = df_all_un.sample(1000)

In [20]:
def get_gender(name):
    try:
        n = name.lower()
        if ('mom' in n) or ('girl' in n) or ('angel' in n) or ('mum' in n) or ('mother' in n) or ('woman' in n):
            return 'female'
        if ('boy' in n) or ('dude' in n):
            return 'male'
        temp = name.translate(translator).split()
    except:
        return 'unknown'
    
    if len(temp)>0:
        first_name = temp[0]
        first_name = ''.join([i for i in first_name if not i.isdigit()])
        gender = d.get_gender(first_name,'usa')
        return gender
    else:
        return 'unknown'

In [10]:
df_sample['Gender'] = df_sample['Name'].apply(lambda x:get_gender(x))

In [12]:
df_sample.sample(100)

,ReviewerID,ProductID,Name,Gender,Helpfulness,Review,Rating,Timestamp
26693203,A3B4LOG41L02J4,B00IG20HPW,CC,unknown,"0,0",Not a bad cover but very stiff plastic. Volume...,3,1.40331e+09
20869501,A2SX0FUBCJXSZZ,1480260231,"L. Baker ""book addict""",unknown,"0,0","Being part English and not always proud of it,...",5,1.3614e+09
39391250,AMS25JBKJGF6D,B0007KLH1Y,M. Weaver,unknown,"0,0",We initially found them at the Brooklyn Childr...,5,1.40365e+09
3961456,A1C3SPBSHB1001,B003I867US,Prasanna Kumar Thoguluva Santharam,unknown,"0,0",I have just started using it. Seems to work fi...,4,1.40098e+09
29794445,A3KWXPNFPL0QRA,0201549794,"R. Hoopes ""aedesc""",unknown,"3,5",This book is perfect. During the past summer I...,5,981417600
38137382,AIU9GKGIQ4T20,B004U75OYG,S.Gomez,unknown,"0,0",don't buy it. its a waste of time and its LITE...,1,1.3271e+09
3284286,A19Z6POQDRRZBB,1492828769,kjk,unknown,"1,1",I've given other books high marks but this was...,5,1378857600
2389833,A177E6WSUSJWSK,B003HJWCMK,Keri093,female,"0,0",I bought this whole set of Sesame Street chara...,5,1.36356e+09
18928407,A2MT8SI0VGY3D6,098251073X,GPong,unknown,"1,1",This is a fresh and inspiring book on support ...,5.0,1372809600
35370942,AA74NFHFQFZJO,B00FE3QHH8,clionapaterson cliona paterson,unknown,"0,0",From litter lout to flesh and blood hero. No s...,5.0,1385164800
24815235,A357V5F3KAMYK3,0373827822,"M. Palmer ""Michelle P.""",unknown,"0,0","I have attempted this book twice now, and twic...",2,1.3837e+09
13910420,A273WZ5RK1LRG3,B009WO7NQO,Morty,unknown,"0,0",This is the first Angry Birds that I have actu...,5,1.36503e+09
8347778,A1PPU7GSCXLN5V,0873648528,DAVID BROOKS,male,"25,42",I HAVE READ THE BOOK AND I FOUND IT TO BE VERY...,4,9.47808e+08
22959156,A2ZFK6V26GJZ6B,B004H2GGZK,linda keedy,female,"2,2",Beret was what I was looking for but there did...,3,1.38646e+09
31857781,A3RCK6TL7TSWAA,B004SP46SK,K Wright,unknown,"0,0",I used it on 5 dogs and it didn't seem to work...,2,1.35311e+09
32975055,A3UVLQ54Z4391L,B003LPTAYI,Daisey,unknown,"0,0",These headphones are excellent. I purchased 1 ...,5,1.39216e+09
38033158,AIIS1WZBSEHFT,B0028U8598,"R. Hillman ""Life learner""",unknown,"0,0","Love the see through lid, which also nests ups...",5.0,1388188800
28614226,A3H6VTP069WRE5,B001AWUWM8,Speedy G,unknown,"0,0",Love these shoes!!! They are super comfortable...,5,1.39735e+09
16454529,A2F265RY0MTE28,B00CZ8I92G,cookiebdaddy,unknown,"0,0",Just play it! You won't regret it. I didn't wa...,5,1379203200
27057022,A3CA8J9XJZ0S8N,B004F44QO8,"L. Seidell ""lily-s2011""",unknown,"1,2",I ordered this phone after reading the encoura...,3.0,1316390400
12042031,A219A3N8P79BIZ,B002Y2QT2K,"Jetjock ""Jet""",unknown,"0,0",we prefer a 2 coffee to 1 chicory misture for ...,5.0,1395360000
30343536,A3MMJEMXBJOJ8H,B005LR7R6W,Carlgo,unknown,"1,1","Solves the fish issue. Yeah, I heat up the big...",5,1.40504e+09
9712959,A1TZWECB1JZLKY,B00G9AVXBA,"Celticstorm76 ""Blessed be""",unknown,"0,0",Very interesting reality tv show. Better then...,4,1.38646e+09
42994316,AY71UJKBM2UO,174179207X,LeeVW,unknown,"0,0","This was nice to have on our trip, but we foun...",3,1.28555e+09
16759803,A2FZRPAJ0QIIS0,B002E1837A,paul harston,male,"3,3",Size is great. small yet full range power. To...,4,1.36253e+09
22843920,A2Z2EAJ5DQGVP7,B0080RWHS8,Ravana,unknown,"0,0","Costume was fine, though the wings could have ...",3,1383696000
17254984,A2HJSMQV5WXQFW,B00FMH9LAQ,kevin,male,"1,1","I really liked it, a bit small, but that's alr...",5.0,1395705600
8289674,A1PJQZNUWBVHLJ,B00GFXRKHW,rita o'leary,female,"0,0",It is really a great album I have converted my...,5.0,1398816000
33060579,A3V5J33SRKSQ6Y,B0001M3MP2,Nine-Mile,unknown,"0,0",I bought this as a Christmas gift for my Grand...,3,1.26939e+09
8065388,A1OUFD95JD8QRJ,B0009P66TU,PDUBB,unknown,"0,0","I feel grown up now with this watch. Big face,...",5.0,1371081600
...,...,...,...,...,...,...,...,...
889050,A12OV3A3WM9HGC,B00028SBLU,wcrews75,unknown,"4,8","We bought this for my 16mo old son, he has eve...",2,1.09754e+09
21546479,A2V0M9SG7AUY5K,B00AOHE7MG,Amazon Customer,unknown,"0,0",Great colours and comfortable shoes. Many comp...,5,1.37886e+09
27100638,A3CFGW64H8KNW8,B00004SSGJ,cross out the eyes,unknown,"0,3",One of these reviewers said that Reggie and th...,5,1.0082e+09
43535234,AZXFS8GCTSQ5R,B003ES5JEC,NF,unknown,"1,1",The movie opens with Batman investigating a me...,4,1.39113e+09
10840057,A1XIWWOFXRSD0V,B00AX3PHV6,Jkaputs,unknown,"0,0",The pins on these make for perfect hook-up wir...,5,1.40046e+09
18674829,A2M0CLLYPBLR6Z,B0044WWLW0,LueAnn Doebber,unknown,"0,0",The head phones are nice and clear wonderful s...,3,1.39769e+09
9281594,A1SNGETMFPDRX4,B0049UKD6I,"Marooned ""Marooned""",unknown,"2,3","Yes it's white, and it's bigger than your regu...",5,1.34663e+09
37360254,AGEK8AFL3TS85,B0063GSL60,your_moms,unknown,"0,0","Great game, decent options, doesn't crash,if w...",4,1.33618e+09
37866371,AHZXCNIUNEXVS,B00BSWRWR8,"Rilee James ""Rilee""",unknown,"0,0","Don't ask me why, but I thought the toy would ...",3,1.38923e+09
19994812,A2Q57MYWTUJXM7,B005PT1N0W,phillip Hammonds,male,"0,0",Fit perfect if this is not factory then its a ...,5,1.38197e+09
10351150,A1W16J9R4DOBEC,B005N9EZRW,"Sherance Brothers ""Sherance M Brothers""",unknown,"2,12","only the youn g crowd will go for yelawolf, se...",1,1324425600
328363,A10XL35S79Z1GM,B005QDRRXE,Spitfire,unknown,"1,1",I bought this apron to use when I'm servicing ...,5,1.38923e+09
31345440,A3PQRUCW1ZGF41,0609608819,THE critic,andy,"3,7",This might have been a good magazine article a...,1,1.11413e+09
34232560,A6LXKCKCBLZCR,6303052207,S.P.Lindsey,unknown,"1,4",whole movie could have been condenser into 10 ...,1,1.38698e+09
4951638,A1F6Q5QT67HKWD,B00GBT8QFA,Claret,unknown,"0,0","Nothing wrong with it, it came as it was descr...",4.0,1403136000
8530619,A1QAS6KQ2A10OL,1477849807,vickiro,unknown,"0,0",didn't finish this one....couldn't get into it...,2,1.40374e+09
16305379,A2ELDTHOXHI3HC,B0000YRU6S,Golf Man,unknown,"0,0",There is not to much to say about an ironing b...,5.0,1392508800
11946809,A20Y9DSV4PP8RL,B004TU2JEW,D. Steiner,unknown,"1,1","It's out of (Grosset and Dunlap) print, last c...",5.0,1399161600
19334162,A2O24FR4LC9Z1M,B00BFWRL3G,Andy62596,mostly_male,"1,1",This is by far the greatest belt i have ever o...,5,1.37195e+09
14079342,A27M5YQP79LOX2,B001BRQSXO,J. Bowlin,unknown,"1,1",Although I really like the concept of this spo...,2,1.27077e+09
26506038,A3AJFV1AW7MXA5,B0009AK57Y,"PeteDude ""Wherever you go, there you are.""",unknown,"0,0",Not sure whether it was that Eccleston dislike...,3.0,1390953600
2222962,A16OT7IWQ1CPUU,B004RAUF2C,janet,female,"0,0",Since it's Christmas everyday at our house thi...,5,1.35933e+09
14558914,A294QTFYPS4AEK,B0055FSN0Y,"A. Bapat ""Gadget Savvy""",unknown,"0,0",This rice cooker is everything I expected. I ...,5.0,1355875200
21492291,A2UUTAMN3ZUO5D,061557226X,loriann,female,"1,1",Ok so we are trying paleo and I got another pa...,2,1.40003e+09
29333143,A3JG9HC8JY4O98,B00007G39G,Mr Joseph M. Goldberg,unknown,"6,6","This toy is great in both modes, but don't und...",5.0,1067731200
16201376,A2E9JPZCS433EV,B0001YJIGW,S. Moore,unknown,"0,0",This is a very handy simple tool to add to you...,5,1.39571e+09
37701600,AHH3E9AATHCQI,081186944X,"E. Hines ""emiline_in_al""",unknown,"2,2",I love cookbooks. I have shelves of them in my...,5,1.30766e+09
40456070,AQ4GG0POBO8LK,B00KE6GGGW,"P. Bheda ""P.B""",unknown,"1,1",Clear concise explanation for anyone to pickup...,4,1402790400
43052768,AYDX1BL8P37ZV,B009HRLWY0,Louise's granddaughter,unknown,"0,0","Easy to apply, looks great. The best eye make...",5,1.39406e+09
41681404,AU0AQ7LXC70C3,B001RMFSDE,ZuluTiger,unknown,"0,0",These stands are such a deal! Amazing deal for...,5,1298332800

In [21]:
df_all_un['Gender'] = df_all_un['Name'].apply(lambda x:get_gender(x))

In [22]:
df_all_un.groupby('Gender').count()

,ReviewerID,ProductID,Name,Helpfulness,Review,Rating,Timestamp
Gender,,,,,,,
andy,1801982,1801982,1801982,1801982,1801623,1801982,1801982
female,3532427,3532427,3532427,3532427,3532098,3532427,3532427
male,1952457,1952457,1952457,1952457,1952138,1952457,1952457
mostly_female,377454,377454,377454,377454,377419,377454,377454
mostly_male,297637,297637,297637,297637,297590,297637,297637
unknown,35587928,35587928,35584379,35587928,35579193,35587928,35587928

In [14]:
df_all_un.sample(100)

,ReviewerID,ProductID,Name,Gender,Helpfulness,Review,Rating,Timestamp
15025805,A2ALSO4IJQYPCP,B00D1FGF00,DG,unknown,"0,0","Amazing price, super soft and light weight. Gr...",5.0,1404086400
38693982,AKKKN5YFYOVT5,B000GDC5KO,"New Cook ""Fan for Life""",unknown,"11,17",I bought this watch for my husband two years a...,1.0,1295222400
40630122,AQNX0WN00JEVE,B00AFZ5OW4,C. Thilmany,unknown,"5,5","This story is a prequel to Charming, a novel f...",3.0,1379721600
9430373,A1T4M91WRZP7WN,0312421702,Dr. Jan B. Newman,unknown,"27,50",I find this book which has gotten such rave re...,1.0,1208476800
40816873,AR9E5A3FNVJ1T,B00CAW96DI,"diane jackson ""d jackson""",female,"0,0",This game really tested my knowledge of the la...,5,1.36788e+09
33589322,A4K5G39MQBRID,B0078YXHVA,Solstice777,unknown,"0,0",I love this little guy. I got a lot of attenti...,4,1.36331e+09
9009762,A1RSTJ0SRDRRBP,B0063Q4JXY,SunnyTex,unknown,"0,0","The Cart served the purpose, though not quite ...",4,1392940800
20492387,A2RPPG5T4Z1GOA,B001UQ5BIY,"TK ""TK""",unknown,"0,0",These shoes are perfect with work clothes or j...,5,1.28598e+09
38809853,AKXAI8OPEU4BT,B00G9JHGWG,"JeWells ""Jane Wells""",unknown,"0,0","While I'm for escapist reading, Traci Tyne Hil...",5,1.38352e+09
4867112,A1EX3TKBGRHT77,B009A116EO,Rus369,andy,"0,3",DIFFICULT GETTING BELT OFFTHE RELEASE IS TOO S...,3,1.38326e+09
17535729,A2IERBUMZBBZMF,1623006740,D.K,unknown,"0,0","Ms. Sinclair is always a "" must buy"" for me an...",4,1.3843e+09
28959576,A3IAET1IH0IMNO,032144972X,DR. SONG,unknown,"6,13",For the price of the book I don't think it a w...,2,1179100800
27095686,A3CEYHA3DDBII1,B00G05L8NW,cmcdon,unknown,"0,0",The flag itself is really nice. The color and ...,3,1.39692e+09
2512241,A17L0O8GMP5KL6,1611099056,"B. Bowse ""music lover""",unknown,"0,0",The impact of this book caught me by surprise....,5,1.39968e+09
14187202,A27YE6NRT0MAFF,B009B1HYQM,itzyro,unknown,"0,1",The chain on this item was broken. Disappointi...,3,1389916800
770557,A12BDJMPEVQ35J,0385735294,"K. Larsen ""Can't read enough""",unknown,"0,0",My son and I are reading this series. At ages...,5,1.39406e+09
9384887,A1SZHCCXKWHTQH,B0009XH6NC,momstudent,female,"0,0",Andis 18485 Home Haircut 10 Piece Haircutting ...,5.0,1345248000
1115229,A13E1OHUWE38RK,B001U233KG,Cama,unknown,"0,0",Love this lamp. It surprised me just how much ...,5,1.39968e+09
4803976,A1EQBHCDKFAU6G,B001VDZ3AC,Country Mom,female,"2,2","I bought this flag, along with a matching gnom...",5.0,1307404800
33297657,A3VW94A50IWF1F,B00537OF3I,brutalpanther,unknown,"0,0",Fan band looks great.But under the cloth stitc...,3,1393286400
41579599,ATOC6U9N1IRHP,B00CDU1H98,ddanger,unknown,"4,7","A good quick read, I don't remember the Amanda...",5.0,1367712000
22062923,A2WMFRF7EP14U7,B0055PH0XA,W. Sweeney,unknown,"0,0","This thing works great, and I'm only holding b...",4,1.37799e+09
29244185,A3J6882D36YRL,B009FZFONO,Ms. Vanessa M. Nizza,unknown,"0,0",I did not think I would like a show about zomb...,5,1358035200
7536528,A1N6I5OQBBT3H5,B001VD84X0,"Oye! ""M""",unknown,"5,7",I play on a casual weekly league. I bought th...,5,1.28105e+09
24513704,A3497NDGXXH92J,B005YQ7YIQ,"thundercloud ""C.B.""",unknown,"6,7",I had some concerns when I first ordered the C...,5,1.26818e+09
9883279,A1UJLBY1FUZWQ6,B005K95U88,Office Girl,female,"4,5",Didn't last quite 7 months.Always had poor fax...,1,1.37575e+09
1914085,A15PS4KWF8HDEM,0374492921,C.A.Smith,unknown,"0,0","This book was poorly written, views were Euroc...",2,1370476800
5973971,A1ID24YJ83XP8F,B00532LO14,bob,male,"0,0",haven't bought an album i dont like. you just ...,5.0,1354579200
2621743,A17X8SY8XOYH8Z,B00AD96CJQ,Murph77,unknown,"0,0",Not true to size. I ordered a large and my dau...,1,1.38516e+09
13278766,A254AA6MKLUAP8,1466227095,TYOUNG62,unknown,"0,3",Downloaded this free book for the kindle fire ...,5,1333238400
...,...,...,...,...,...,...,...,...
27436629,A3DH1HUC6W42GP,B002OKLUGW,Darienne Coffee,unknown,"0,0",They're super cheap and came really fast. It w...,5,1382832000
25096978,A363S2SDOL4S8,0811813762,julie rast seaton,female,"1,1",The recipes are outstanding - they take me bac...,5,1.36253e+09
39606442,ANFGOF2981VMK,B001HPD4HI,Prufreader,unknown,"0,0",I replaced an older style radiant top on my 20...,5.0,1401926400
589007,A11QLLLK1ELWX8,B0012N9RKS,Amazon Customer,unknown,"0,6",I LOVE MY NEW HEADUNIT IT IS AWESOME AND NO ON...,5.0,1207699200
20480321,A2ROCYE37T62XV,0446532681,"T. Grasso ""tgrasso""",unknown,"0,0",John Stewart reviews the history and political...,5,1.11326e+09
22673316,A2YIU1M3N07VGB,B005KB86TQ,kenshetta jenkins,unknown,"0,0",The Whole Series Is Addictive!!...Sam And Nick...,5,1361145600
20791975,A2SO2P9090L3TS,B000R7G9JW,J R Sound Police,unknown,"5,7",Do not buy this film if you are looking for an...,4,1189814400
37182165,AFVERTG14V1ST,B0009UC7PC,J. Looney,unknown,"0,0",I got this DVD for my 2 1/2 year old and not o...,5.0,1129248000
21087759,A2TLSMB620JCC,B0016HM77A,diana lopatinsky,female,"0,0",VEDRY GOOD PRODUCT BUT ITS VERY HARD TO OPEN A...,4.0,1372032000
43440574,AZMGDFBUMI5MM,B004VMUS9G,Amazon Customer,unknown,"0,0",Does exactly what I need it to do. Can set mul...,5,1.36382e+09
17937483,A2JOPC9SKDY5C2,B00004RHZU,mizparker,unknown,"0,0",This is by far Pink's best album ever! I purch...,5,1.35147e+09
15800978,A2D0MBRCNF918U,B000FKGIGK,"K. Yu ""Saw the movie, now I'm going to read t...",unknown,"0,0",This is the only moisturizer I'm not allergic ...,5,1.21876e+09
13883539,A270PZHNNY16UY,B00CKW6FVE,fchchdjd,unknown,"0,0",I absolutely love this game. I've been waiting...,5,1.37013e+09
34648073,A7Y2RAZZRFVI3,0500281947,Lannes J. Hilboldt,unknown,"0,0",i bought this because I am a theatre director ...,4,1394668800
31745318,A3R039LAEWJ452,B0073F92OK,NicMarson,unknown,"0,0","I have a Samsung Galaxy Sii, which bleeds batt...",5,1.35173e+09
39028132,ALMHV32FP0GZU,B00AMMFQTG,Amazon Customer,unknown,"1,1",I have been a long time fan of Heather Long's ...,5,1.36279e+09
42406876,AWB5SI9UOQK5,080419257X,Amazon Customer,unknown,"3,3",This might be the first book i give a 5/5 rati...,5.0,1388275200
9212563,A1SFGBHMOB5JKW,B0042ESGME,J. Hesketh,unknown,"0,0",My daughter got 2 sets of these for her birthd...,4.0,1342224000
18668531,A2LZMCRIVJT1MK,B003YUBQL0,Ed-Rod74,unknown,"0,5",havent used it yet a gift for the daughter nex...,4,1.30792e+09
16584314,A2FG61IY8UICWH,B008CTMQDA,MlleCM,unknown,"0,1","Loved these glasses -- the shape, not the qual...",3,1.39044e+09
39408416,AMTZGSAPH0TCS,B001V98S2G,omommy248,female,"0,0",I watched this sow back in the day on regular ...,5,1.40028e+09
29349635,A3JI5QP2K5AOKV,B000SOOHTS,yvette robbins,andy,"0,0",The vacuum that the filter fits into is many y...,5.0,1373846400
37213767,AFYR34MOHW8Y,B0093DRQ6G,a.j.,unknown,"0,0","Loved this book. Sophie is a charmer, warts a...",5.0,1356134400
24460353,A3439J4C22WCBU,B00361T7CW,"MH ""MH""",unknown,"0,0",My 12 year old daugter wanted a Twight Light t...,5.0,1359331200
10158797,A1VF61FAZL2S56,0143057367,Neesha,unknown,"0,0",With me being in my last semester of college a...,5,1.34957e+09
17390979,A2HYLAK74PY39N,B00275LC76,sonam,unknown,"1,1",Unlike other cleaning cloths these skoy cloths...,5,1.36927e+09
15238449,A2B9T4SXBYKWCW,B001UI4RTG,Geoworker,unknown,"1,1",Using this device on my network right now. Wor...,5.0,1384732800
4928250,A1F3Z569PMTRA,B005OWHHK0,nirisha,unknown,"0,0",This is really good. I am happy with this stuf...,5.0,1371081600
26830632,A3BKE2XQ94SZ3K,1442361514,Mardella,unknown,"0,0",It was a very moving story. It makes you wonde...,5,1.38542e+09
30178061,A3M41Z7ODYQWL4,B003M6E0FU,vicki burkhart,female,"0,0",good fit for my big guy and has big openings f...,5.0,1337644800

In [36]:
df_all_un_male = df_all_un[df_all_un['Gender']=='male']

In [37]:
df_all_un_female = df_all_un[df_all_un['Gender']=='female']

In [38]:
df_all_un_male.count()

ReviewerID     1952808
ProductID      1952808
Name           1952808
Gender         1952808
Helpfulness    1952468
Review         1952149
Rating         1952468
Timestamp      1952468
dtype: int64

In [39]:
df_all_un_female.count()

ReviewerID     3532942
ProductID      3532942
Name           3532942
Gender         3532942
Helpfulness    3532450
Review         3532121
Rating         3532450
Timestamp      3532450
dtype: int64

In [42]:
df_all_un_m_male = df_all_un[df_all_un['Gender']=='mostly_male']

In [43]:
df_all_un_m_female = df_all_un[df_all_un['Gender']=='mostly_female']

In [44]:
df_all_un_m_female.count()

ReviewerID     377551
ProductID      377551
Name           377551
Gender         377551
Helpfulness    377459
Review         377424
Rating         377459
Timestamp      377459
dtype: int64

In [23]:
df_all_un_un = df_all_un[(df_all_un['Gender']=='unknown')|(df_all_un['Gender']=='andy')]

In [24]:
df_all_un_un.count()

ReviewerID     37389910
ProductID      37389910
Name           37386361
Gender         37389910
Helpfulness    37389910
Review         37380816
Rating         37389910
Timestamp      37389910
dtype: int64

In [47]:
df_all_un_male.to_csv('amazon_male_more.csv',sep='|')

In [48]:
df_all_un_female.to_csv('amazon_female_more.csv',sep='|')

In [49]:
df_all_un_m_female.to_csv('amazon_m_female_more.csv',sep='|')

In [50]:
df_all_un_m_male.to_csv('amazon_m_male_more.csv',sep='|')

In [51]:
df_m_male = pd.read_csv('amazon_mostly_male.csv', names=['ReviewerID', 'ProductID', 'Name', 'Gender','Helpfulness', 'Review', 'Rating','Timestamp'],sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [52]:
df_m_male.count()

ReviewerID     1455919
ProductID      1455919
Name           1455919
Gender         1455919
Helpfulness    1455919
Review         1455445
Rating         1455919
Timestamp      1455919
dtype: int64

In [70]:
df_m_male['Gender'] = df_m_male['Name'].apply(lambda x:get_gender(x))

In [72]:
df_m_male.groupby('Gender').count()

,ReviewerID,ProductID,Name,Helpfulness,Review,Rating,Timestamp
Gender,,,,,,,
andy,167954,167954,167954,167954,167910,167954,167954
female,17391,17391,17391,17391,17387,17391,17391
male,43079,43079,43079,43079,43066,43079,43079
mostly_female,93097,93097,93097,93097,93083,93097,93097
mostly_male,1134398,1134398,1134398,1134398,1133999,1134398,1134398

In [73]:
df_m_male_m = df_m_male[df_m_male['Gender']=='male']

In [74]:
df_m_male_f = df_m_male[df_m_male['Gender']=='female']

In [75]:
df_m_male_m_male = df_m_male[df_m_male['Gender']=='mostly_male']

In [76]:
df_m_male_m_female = df_m_male[df_m_male['Gender']=='mostly_female']

In [77]:
df_m_male_unk = df_m_male[df_m_male['Gender']=='andy']

In [78]:
df_m_female = pd.read_csv('amazon_mostly_female.csv', names=['ReviewerID', 'ProductID', 'Name', 'Gender','Helpfulness', 'Review', 'Rating','Timestamp'],sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [79]:
df_m_female['Gender'] = df_m_female['Name'].apply(lambda x:get_gender(x))

In [81]:
df_m_female.groupby('Gender').count()

,ReviewerID,ProductID,Name,Helpfulness,Review,Rating,Timestamp
Gender,,,,,,,
andy,283934,283934,283934,283934,283858,283934,283934
female,52210,52210,52210,52210,52201,52210,52210
male,10918,10918,10918,10918,10915,10918,10918
mostly_female,1806708,1806708,1806708,1806708,1806494,1806708,1806708
mostly_male,71030,71030,71030,71030,71003,71030,71030
unknown,1,1,1,1,1,1,1

In [82]:
df_m_female_m = df_m_female[df_m_female['Gender']=='male']

In [83]:
df_m_female_f = df_m_female[df_m_female['Gender']=='female']

In [84]:
df_m_female_m_male = df_m_female[df_m_female['Gender']=='mostly_male']

In [85]:
df_m_female_m_female = df_m_female[df_m_female['Gender']=='mostly_female']

In [86]:
df_m_female_unk = df_m_female[(df_m_female['Gender']=='andy')|(df_m_female['Gender']=='unknown')]

In [87]:
df_male = pd.concat([df_all_un_male,df_m_male_m,df_m_female_m]) # all male

In [88]:
df_female = pd.concat([df_all_un_female,df_m_male_f,df_m_female_f]) # all female

In [90]:
df_female.count()

ReviewerID     3602543
ProductID      3602543
Name           3602543
Gender         3602543
Helpfulness    3602051
Review         3601709
Rating         3602051
Timestamp      3602051
dtype: int64

In [91]:
df_mostly_male = pd.concat([df_all_un_m_male,df_m_male_m_male,df_m_female_m_male]) # all_mostly_male

In [92]:
df_mostly_female = pd.concat([df_all_un_m_female,df_m_male_m_female,df_m_female_m_female]) # all_mostly_female

In [93]:
df_unk = pd.concat([df_all_un_un,df_m_male_unk,df_m_female_unk]) # all_unknown

In [94]:
df_male.to_csv('amazon_gender_new/amazon_male_more.csv',sep='|')

In [95]:
df_female.to_csv('amazon_gender_new/amazon_female_more.csv',sep='|')

In [26]:
df_all_un_un.to_csv('../amazon_gender_new/amazon_unknown.csv',sep='|',index=False)

In [97]:
df_mostly_female.to_csv('amazon_gender_new/amazon_mostly_female.csv',sep='|')

In [98]:
df_mostly_male.to_csv('amazon_gender_new/amazon_mostly_male.csv',sep='|')

In [3]:
df_male_1 = pd.read_csv('amazon_male.csv', names=['ReviewerID', 'ProductID', 'Name', 'Gender','Helpfulness', 'Review', 'Rating','Timestamp'],sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df_male_2 = pd.read_csv('amazon_gender_new/amazon_male_more.csv',sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df_male_1.columns

Index(['ReviewerID', 'ProductID', 'Name', 'Gender', 'Helpfulness', 'Review',
       'Rating', 'Timestamp'],
      dtype='object')

In [6]:
df_male_2.columns

Index(['Unnamed: 0', 'ReviewerID', 'ProductID', 'Name', 'Gender',
       'Helpfulness', 'Review', 'Rating', 'Timestamp'],
      dtype='object')

In [10]:
df_male_2.count()

Unnamed: 0     2006805
ReviewerID     2006805
ProductID      2006805
Name           2006805
Gender         2006805
Helpfulness    2006465
Review         2006130
Rating         2006465
Timestamp      2006465
dtype: int64

In [9]:
df_male_1.count()

ReviewerID     16948006
ProductID      16948006
Name           16948006
Gender         16948006
Helpfulness    16948006
Review         16942720
Rating         16948006
Timestamp      16948006
dtype: int64

In [13]:
df_male_2 = df_male_2.drop(columns=['Unnamed: 0'])

In [14]:
df_male_2.columns

Index(['ReviewerID', 'ProductID', 'Name', 'Gender', 'Helpfulness', 'Review',
       'Rating', 'Timestamp'],
      dtype='object')

In [15]:
df_male_all = pd.concat([df_male_1,df_male_2])

In [16]:
df_male_all.count()

ReviewerID     18954811
ProductID      18954811
Name           18954811
Gender         18954811
Helpfulness    18954471
Review         18948850
Rating         18954471
Timestamp      18954471
dtype: int64

In [17]:
df_male_all.to_csv('amazon_gender_new/amazon_male_all.csv',sep='|',index=False)

In [18]:
df_female_1 = pd.read_csv('amazon_female.csv', names=['ReviewerID', 'ProductID', 'Name', 'Gender','Helpfulness', 'Review', 'Rating','Timestamp'],sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
df_female_2 = pd.read_csv('amazon_gender_new/amazon_female_more.csv',sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [20]:
df_female_2 = df_female_2.drop(columns=['Unnamed: 0'])

In [21]:
df_female_all = pd.concat([df_female_1,df_female_2])

In [22]:
df_female_all.count()

ReviewerID     19367077
ProductID      19367077
Name           19367077
Gender         19367077
Helpfulness    19366585
Review         19364580
Rating         19366585
Timestamp      19366585
dtype: int64

In [23]:
df_female_all.to_csv('amazon_gender_new/amazon_female_all.csv',sep='|',index=False)

In [2]:
df = pd.read_csv('../amazon_gender_new/amazon_unknown.csv',sep='|')

/opt/anaconda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.columns

Index(['Unnamed: 0', 'ReviewerID', 'ProductID', 'Name', 'Gender',
       'Helpfulness', 'Review', 'Rating', 'Timestamp'],
      dtype='object')

In [7]:
df = df.drop(columns=['Unnamed: 0'])

In [8]:
df.columns

Index(['ReviewerID', 'ProductID', 'Name', 'Gender', 'Helpfulness', 'Review',
       'Rating', 'Timestamp'],
      dtype='object')

In [13]:
df.count()

ReviewerID     37848341
ProductID      37847772
Name           37844223
Gender         37848343
Helpfulness    37845424
Review         37836210
Rating         37842109
Timestamp      37842109
dtype: int64

In [24]:
df.iloc[108421]

ReviewerID                                        A10APATH8GPXAI
ProductID                                             B0060JK23U
Name                                                     KLMCats
Gender                                                   unknown
Helpfulness                                                  0,0
Review         I purchased on recommendation of a friend. Hav...
Rating                                                         4
Timestamp                                            1.40167e+09
Name: 108421, dtype: object

In [21]:
df.sample(300)['Name']

33230427                           JH
25885432                        BBano
27465026                         ozfx
36651516                      scigeek
27450996                 Charger user
37079685                   Fiana cruz
31867284              Amazon Customer
15013209                    R. Dekema
34777814           t m cruz dominguez
3020977                    MamavanMNE
23237687               C. Karu "Karu"
4888472               Amazon Customer
10600630                    Natty Sue
12588195                          DWF
24601954                      shaffer
5810087               Honest Consumer
24550084                 kim*designer
396724                   Chenna Latta
12699534                 masandra1026
12322403                      Carpria
36808580                   J. Baldwin
36114869                   Queenbeans
3519382                       carlson
16874190       K. S. "Costa Rica Kim"
26427130                        Zgina
27597901                      O. Mora
28872322                   R. L Shane
7441458                    Dare2Dream
7255037                     Anonymous
32397205    flippityjib "flippityjib"
                      ...
28267445                  sanghamitra
12091135                  M. Bradshaw
30915066                  simplyfoote
10477689                        DaveA
325811                          Koepp
33365850                   Babe "MsH"
8485037                            Su
8189100               Amazon Customer
21716520                           MW
811331                   ProfreadingP
17000987                    S. Potter
10436126                         wolf
35003887                       OddJob
10702947                        Ryner
13788296           Dr. A. L. Stoddard
25709597                      BClark7
22234804                      A. Loof
11657987                 Staff Writer
18740907                     78zinman
5196228                     Writeguy1
14150246                        BethF
27804953                       BClyde
21153515      G. Robinson "MDS Queen"
28094785                 C. Zimmerman
29515643                       Aussie
7974756                    Parisienne
9672644                 walleyeslayer
26418274                stockprincess
17100175                            M
5813046                     B. Rohrig
Name: Name, Length: 300, dtype: object

In [1]:
import torch

ModuleNotFoundError: No module named 'torch'